name: Project

on:
  push:
    branches:
      - main
    paths:
      - project/**

jobs:
  exercise-feedback:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          path: app

      - name: Add Kaggle API credentials
        run: |
          mkdir -p ~/.kaggle
          echo "${{ secrets.KAGGLE_JSON }}" > ~/.kaggle/kaggle.json
          chmod 600 ~/.kaggle/kaggle.json 

      - name : Starting Pipeline
        working-directory: ./app/project
        run : bash datapipeline.sh

      - name : Starting Test
        working-directory: ./app/project
        run : bash Automated_test.sh