name: Project Tests
on:
  push:
    branches:
      - main
    paths:
      - project/**

jobs:
  project_test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python 3.11
        uses: actions/setup-python@v4
        with:
          python-version: 3.11
    
      - name: Install dependencies
        run: pip install kaggle requests pandas pysqlite3 matplotlib seaborn scikit-learn

      - name: Run Data Pipeline
        run: bash project/datapipeline.sh

      - name: Run Automated Tests
        run: bash project/Automated_test.sh
